name: Deploy NestJS with Prisma and Redis to VPS using Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            echo "ğŸ“ Creating project folder if it doesn't exist..."
            mkdir -p ~/azizbek
            cd ~/azizbek

            if [ ! -d "sanatoriya_backend" ]; then
              echo "ğŸš€ Cloning repository..."
              git clone https://github.com/aziz-davronov107/sanatoriya_backend.git
            else
              echo "ğŸ“¦ Pulling latest changes..."
              cd sanatoriya_backend
              git reset --hard origin/main
              git pull origin main
            fi
            cd ~/azizbek/sanatoriya_backend

            echo "ğŸ‘¨â€ğŸ”§ Giving Docker permissions..."
            sudo usermod -aG docker $USER || true

            echo "ğŸ›‘ Stopping containers..."
            docker compose down || true

            echo "ğŸ”¨ Building containers..."
            docker compose build

            echo "ğŸš€ Starting containers..."
            docker compose up -d
            

            echo "âœ… Deployment finished!"